#!/bin/bash
#
# Configure nodejs
set -u

echo "========== node.js =========="

readonly NODE_VERSION="22.14.0"


function nodenv_install() {
  if ! type -p nodenv > /dev/null 2>&1; then
    return 0
  fi
  eval "$(nodenv init -)"
  nodenv install $NODE_VERSION
  nodenv global $NODE_VERSION
  nodenv rehash
}

function npm_packages() {
  if type -p npm > /dev/null 2>&1; then
    npm update -g npm
    npm install -g degit
  fi
}

function main() {
  nodenv_install
  npm_packages
}

main "$@"

echo "done."
