#!/bin/bash
#
# Configure (python)
set -u

echo "========== (python) =========="

readonly PYTHON_VERSION="3.9.14"

function pyenv_install() {
  if ! type -p pyenv > /dev/null 2>&1; then
    return 0
  fi
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
  # WORKAROUND: https://qiita.com/craymaru/items/58e92fac99b5b0ec778f
  #
  if type -p xcrun > /dev/null 2>&1; then
    LDFLAGS="-L$(xcrun --show-sdk-path)/usr/lib" pyenv install $PYTHON_VERSION
  else
    pyenv install $PYTHON_VERSION
  fi
  pyenv global $PYTHON_VERSION
  pyenv rehash
}

function pip_install() {
  local -r is_valid=$(python -V | grep -c "${PYTHON_VERSION}")
  if [[ $is_valid -eq 0 ]]; then
    echo "[skip] ${PYTHON_VERSION} not installed."
    return 0
  fi
  if ! type -p pip > /dev/null 2>&1; then
    return 0
  fi
  pip install -U pip
  pip install pipx
}

function pipx_install() {
  if ! type -p pipx > /dev/null 2>&1; then
    return 0
  fi
  pipx install termtosvg
  pipx install adb-enhanced
  pipx install urlscan
  pipx install jc
  pipx install fb-idb
}

function poetry_install() {
  if ! type -p poetry > /dev/null 2>&1; then
    curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  fi

  # shellcheck disable=SC1090
  source "$HOME"/.poetry/env
  poetry completions fish > "$HOME"/.config/fish/completions/poetry.fish
}

function main() {
  pyenv_install
  pip_install
  pipx_install
  poetry_install
}

main "$@"

echo "done."
