#!/bin/bash
#
# Configure (python)
set -u

echo "========== (python) =========="

function uv_tool_install() {
  if ! type -p uv > /dev/null 2>&1; then
    return 0
  fi
  uv tool install jc
  uv tool install fb-idb
}

function main() {
  uv_tool_install
}

main "$@"

echo "done."
