#!/bin/bash
#
# Configure (golang)
set -u

echo "========== (golang) =========="

declare -xr GO111MODULE=on

function get_install() {
  if ! type -p go > /dev/null 2>&1; then
    return 0
  fi
  go install github.com/arsham/blush@latest
  go install github.com/google/yamlfmt/cmd/yamlfmt@latest
  go install github.com/plutov/oq@latest
}

function main() {
  get_install
}

main "$@"

echo "done."
