#!/bin/bash
#
# Configure (homesick)
set -u

echo "========== (homesick) =========="

function link_dotfiles() {
  homesick link dotfiles
}

function main() {
  link_dotfiles
}

main "$@"

echo "done."
