#!/bin/bash
#
# Configure homebrew

echo "========== homebrew =========="

if ! type -p brew > /dev/null 2>&1; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo $(homesick show_path dotfiles)
#brew bundle --file=../Brewfile
